[install]
is_configured = 1

[ui]
is_visible = 1
label = PAN Check

[launcher]
author = Navid Alizadeh
description = Splunk custom streaming search command for PAN validation using the Luhn algorithm.
version = 1.0.0
